import Head from 'next/head'

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Airbnb</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="bg-red-300 text-white">Airbnb Clone starter template</div>
    </div>
  )
}
